module OrdersHelper
  TOWNS = [
    "Abbey St, Dublin City North, Ireland",
    "Abbey Wood, London SE, London",
    "Abbots Langley, Watford, London",
    "Aberaeron, Swansea, Wales",
    "Aberdare, Cardiff, Wales",
    "Aberdeen, Aberdeen, Scotland",
    "Aberdovey, Llandudno, Wales",
    "Aberfeldy,Acharacle, Perth, Scotland",
    "Abergavenny, Newport, Wales",
    "Abergele, Llandudno, Wales",
    "Aberlour, Aberdeen, Scotland",
    "Abertillery, Newport, Wales",
    "Aberystwyth, Shrewsbury, Wales",
    "Abingdon, Oxford, South East",
    "Aboyne, Aberdeen, Scotland",
    "Accrington, Blackburn, North West",
    "Achnasheen, Inverness, Scotland",
    "Acton, London W, London",
    "Addlestone, Kingston upon Thames, London",
    "Airdrie, Motherwell, Scotland",
    "Alcester, Birmingham, The Midlands",
    "Aldeburgh, Ipswich, East Anglia",
    "Alderley Edge, Stockport, North West",
    "Aldershot, Guildford, South East",
    "Alexandria, Glasgow, Scotland",
    "Alford, Aberdeen, Scotland",
    "Alford, Lincoln, East Anglia",
    "Alfreton, Derby, The Midlands",
    "Alloa, Falkirk, Scotland",
    "Alness, Inverness, Scotland",
    "Alnwick, Newcastle upon Tyne, North East",
    "Alresford, Southampton, South East",
    "Alston, Carlisle, North West",
    "Alton, Guildford, South East",
    "Altrincham, Warrington, North West",
    "Alva, Falkirk, Scotland",
    "Ambleside, Lancaster, North West",
    "Amersham, Hemel Hempstead, South East",
    "Amiens St, Dublin City North, Ireland",
    "Amlwch, Llandudno, Wales",
    "Ammanford, Swansea, Wales",
    "Andover, Salisbury, South West",
    "Annan, Dumfries, Scotland",
    "Anstruther, Kirkcaldy, Scotland",
    "Antrim, Belfast, Northern Ireland",
    "Appin, Paisley, Scotland",
    "Appleby In Westmorland, Carlisle, North West",
    "Arbout Hill, Dublin North, Ireland",
    "Arbroath, Dundee, Scotland",
    "Ardee, Louth, Ireland",
    "Ardgay, Inverness, Scotland",
    "Ardrossan, Kilmarnock, Scotland",
    "Arisaig, Perth, Scotland",
    "Arklow, Wicklow, Ireland",
    "Arlesey, Stevenage, East Anglia",
    "Armagh, Belfast, Northern Ireland",
    "Arrochar, Glasgow, Scotland",
    "Artane, Dublin North, Ireland",
    "Arthog, Llandudno, Wales",
    "Arundel, Brighton, South East",
    "Ascot, Slough, London",
    "Ashbourne, Derby, The Midlands",
    "Ashbourne, Meath, Ireland",
    "Ashby-De-La-Zouch, Leicester, The Midlands",
    "Ashford, Tonbridge, South East",
    "Ashford, Twickenham, London",
    "Ashington, Newcastle upon Tyne, North East",
    "Ashtead, Kingston upon Thames, London",
    "Ashton-Under-Lyne, Oldham, North West",
    "Askam-In-Furness, Lancaster, North West",
    "Atherstone, Coventry, The Midlands",
    "Athlone, Westmeath, Ireland",
    "Athy, Kildare, Ireland",
    "Attleborough, Norwich, East Anglia",
    "Auchterarder, Perth, Scotland",
    "Augher, Belfast, Northern Ireland",
    "Aughnacloy, Belfast, Northern Ireland",
    "Aviemore, Perth, Scotland",
    "Avoch, Inverness, Scotland",
    "Axbridge, Bristol, South West",
    "Axminster, Exeter, South West",
    "Aylesbury, Hemel Hempstead, South East",
    "Aylesford, Rochester, South East",
    "Ayr, Kilmarnock, Scotland",
    "Bacup, Oldham, North West",
    "Badminton, Gloucester, South West",
    "Baggot St Upper, and Lower, Dublin City South, Ireland",
    "Bagillt, Chester, North West",
    "Bagshot, Guildford, South East",
    "Baily, Dublin North, Ireland",
    "Bakewell, Derby, The Midlands",
    "Bala, Llandudno, Wales",
    "Balbriggan, Dublin, Ireland",
    "Baldock, Stevenage, East Anglia",
    "Baldoyle, Dublin North, Ireland",
    "Balerno, Edinburgh, Scotland",
    "Balgrifin, Dublin North, Ireland",
    "Balham, London SW, London",
    "Ballachulish, Perth, Scotland",
    "Ballater, Aberdeen, Scotland",
    "Ballina, Mayo, Ireland",
    "Ballinasloe, Galway, Ireland",
    "Ballindalloch, Aberdeen, Scotland",
    "Ballinteer, Dublin South, Ireland",
    "Ballsbridge, Dublin South, Ireland",
    "Ballyboden, Dublin South, Ireland",
    "Ballybofey-Stranorlar, Donegal, Ireland",
    "Ballybough, Dublin North, Ireland",
    "Ballycastle, Belfast, Northern Ireland",
    "Ballyclare, Belfast, Northern Ireland",
    "Ballyedmonduff, Dublin South, Ireland",
    "Ballyfermot , Dublin South, Ireland",
    "Ballygal, Dublin North, Ireland",
    "Ballymena, Belfast, Northern Ireland",
    "Ballymoney, Belfast, Northern Ireland",
    "Ballynahinch, Belfast, Northern Ireland",
    "Bamburgh, Newcastle upon Tyne, North East",
    "Bampton, Oxford, South East",
    "Banbridge, Belfast, Northern Ireland",
    "Banbury, Oxford, South East",
    "Banchory, Aberdeen, Scotland",
    "Bandon County Cork, Cork, Ireland",
    "Banff, Aberdeen, Scotland",
    "Bangor, Belfast, Northern Ireland",
    "Bangor, Llandudno, Wales",
    "Bank Of England, London EC, London",
    "Banstead, Sutton, London",
    "Bantry, Cork, Ireland",
    "Banwell, Bristol, South West",
    "Barbican, London EC, London",
    "Bargoed, Cardiff, Wales",
    "Barking, Ilford, London",
    "Barmouth, Llandudno, Wales",
    "Barnard Castle, Darlington, North East",
    "Barnes, London SW, London",
    "Barnet, Enfield, London",
    "Barnetby, Doncaster, Yorkshire",
    "Barnoldswick, Blackburn, North West",
    "Barnsley, Sheffield, Yorkshire",
    "Barnstaple, Exeter, South West",
    "Barrow Upon Humber, Doncaster, Yorkshire",
    "Barrow-In-Furness, Lancaster, North West",
    "Barry, Cardiff, Wales",
    "Barton Upon Humber, Doncaster, Yorkshire",
    "Basildon, Southend on Sea, East Anglia",
    "Basingstoke, Reading, South East",
    "Bath, Bath, South West",
    "Bathgate, Edinburgh, Scotland",
    "Batley, Wakefield, Yorkshire",
    "Battle, Tonbridge, South East",
    "Bawnogue, Dublin South, Ireland",
    "Bayside, Dublin North, Ireland",
    "Beaconsfield, Hemel Hempstead, South East",
    "Beaminster, Dorchester, South West",
    "Beauly, Inverness, Scotland",
    "Beaumaris, Llandudno, Wales",
    "Beaumont, Dublin North, Ireland",
    "Beaworthy, Exeter, South West",
    "Beccles, Norwich, East Anglia",
    "Beckenham, Bromley, London",
    "Beckermet, Carlisle, North West",
    "Bedale, Darlington, North East",
    "Bedford, Milton Keynes, London",
    "Bedlington, Newcastle upon Tyne, North East",
    "Bedworth, Coventry, The Midlands",
    "Beith, Kilmarnock, Scotland",
    "Belcamp, Dublin North, Ireland",
    "Belfast, Belfast, Northern Ireland",
    "Belford, Newcastle upon Tyne, North East",
    "Bellshill, Motherwell, Scotland",
    "Belper, Derby, The Midlands",
    "Belvedere, Dartford, South East",
    "Bembridge, Portsmouth, South East",
    "Benfleet, Southend on Sea, East Anglia",
    "Berkeley, Gloucester, South West",
    "Berkhamsted, Hemel Hempstead, South East",
    "Bermondsey, London SE, London",
    "Berriedale, Kirkwall, Scotland",
    "Berwick-Upon-Tweed, Galashiels, Scotland",
    "Betchworth, Redhill, South East",
    "Bethnal Green, London E, London",
    "Betws-Y-Coed, Llandudno, Wales",
    "Beverley, Hull, Yorkshire",
    "Bewdley, Dudley, The Midlands",
    "Bexhill-On-Sea, Tonbridge, South East",
    "Bexley, Dartford, South East",
    "Bexleyheath, Dartford, South East",
    "Bicester, Oxford, South East",
    "Bideford, Exeter, South West",
    "Biggar, Motherwell, Scotland",
    "Biggleswade, Stevenage, East Anglia",
    "Billericay, Chelmsford, East Anglia",
    "Billingham, Cleveland, North East",
    "Billingshurst, Redhill, South East",
    "Bilston, Wolverhampton, The Midlands",
    "Bingley, Bradford, Yorkshire",
    "Birchington, Canterbury, South East",
    "Birkenhead, Chester, North West",
    "Birmingham, Birmingham, The Midlands",
    "Birr, Offaly, Ireland",
    "Bishop Auckland, Darlington, North East",
    "Bishops Castle, Shrewsbury, Wales",
    "Bishops Stortford, Chelmsford, East Anglia",
    "Bishopsgate, London EC, London",
    "Bishopton, Paisley, Scotland",
    "Blackburn, Blackburn, North West",
    "Blackfriars, London EC, London",
    "Blackheath, London SE, London",
    "Blackpool, Blackpool, North West",
    "Blackwood, Newport, Wales",
    "Blaenau Ffestiniog, Llandudno, Wales",
    "Blairgowrie, Perth, Scotland",
    "Blakeney, Gloucester, South West",
    "Blanchardstown, Dublin North, Ireland",
    "Blandford Forum, Dorchester, South West",
    "Blaydon-On-Tyne, Newcastle upon Tyne, North East",
    "Blessington, Wicklow, Ireland",
    "Bloomsbury, London WC, London",
    "Bluebell, Dublin South, Ireland",
    "Blyth, Newcastle upon Tyne, North East",
    "Bo'Ness, Edinburgh, Scotland",
    "Boat Of Garten, Perth, Scotland",
    "Bodmin, Plymouth, South West",
    "Bodorgan, Llandudno, Wales",
    "Bognor Regis, Portsmouth, South East",
    "Boldon Colliery, Newcastle upon Tyne, North East",
    "Bolton, Bolton, North West",
    "Boncath, Swansea, Wales",
    "Bonnybridge, Falkirk, Scotland",
    "Bonnyrigg, Edinburgh, Scotland",
    "Bootle, Liverpool, North West",
    "Bordon, Guildford, South East",
    "Borehamwood, Watford, London",
    "Borth, Shrewsbury, Wales",
    "Boscastle, Plymouth, South West",
    "Boston, Peterborough, East Anglia",
    "Bourne End, Slough, London",
    "Bourne, Peterborough, East Anglia",
    "Bournemouth, Bournemouth, South East",
    "Bow Street, Shrewsbury, Wales",
    "Bow, London E, London",
    "Brackley, Northampton, South East",
    "Bracknell, Reading, South East",
    "Bradford On Avon, Bath, South West",
    "Bradford, Bradford, Yorkshire",
    "Braintree, Chelmsford, East Anglia",
    "Brampton, Carlisle, North West",
    "Brandon, Ipswich, East Anglia",
    "Braunton, Exeter, South West",
    "Bray, Wicklow, Ireland",
    "Brechin, Dundee, Scotland",
    "Brecon, Llandrindod Wells, Wales",
    "Brentford, Twickenham, London",
    "Brentwood, Chelmsford, East Anglia",
    "Bridge Of Orchy, Paisley, Scotland",
    "Bridge Of Weir, Paisley, Scotland",
    "Bridgend, Cardiff, Wales",
    "Bridgnorth, Wolverhampton, The Midlands",
    "Bridgwater, Taunton, South West",
    "Bridlington, York, Yorkshire",
    "Bridport, Dorchester, South West",
    "Brierley Hill, Dudley, The Midlands",
    "Brigg, Doncaster, Yorkshire",
    "Brighouse, Huddersfield, Yorkshire",
    "Brighton, Brighton, South East",
    "Bristol, Bristol, South West",
    "Brixham, Torquay, South West",
    "Brixton, London SW, London",
    "Broadgate, London EC, London",
    "Broadstairs, Canterbury, South East",
    "Broadstone, Bournemouth, South East",
    "Broadway, Worcester, The Midlands",
    "Brockenhurst, Southampton, South East",
    "Brockley, London SE, London",
    "Bromley, Bromley, London",
    "Bromsgrove, Birmingham, The Midlands",
    "Bromyard, Hereford, The Midlands",
    "Brora, Kirkwall, Scotland",
    "Broseley, Telford, The Midlands",
    "Brough, Hull, Yorkshire",
    "Broughton-In-Furness, Lancaster, North West",
    "Broxbourne, Enfield, London",
    "Broxburn, Edinburgh, Scotland",
    "Bruton, Bath, South West",
    "Brynteg, Llandudno, Wales",
    "Buckfastleigh, Torquay, South West",
    "Buckhurst Hill, Ilford, London",
    "Buckie, Aberdeen, Scotland",
    "Buckingham, Milton Keynes, London",
    "Buckley, Chester, North West",
    "Bucknell, Shrewsbury, Wales",
    "Bude, Exeter, South West",
    "Budleigh Salterton, Exeter, South West",
    "Builth Wells, Llandrindod Wells, Wales",
    "Buncrana, Donegal, Ireland",
    "Bungay, Norwich, East Anglia",
    "Buntingford, Stevenage, East Anglia",
    "Bures, Colchester, East Anglia",
    "Burford, Oxford, South East",
    "Burgess Hill, Redhill, South East",
    "Burnham On Crouch, Chelmsford, East Anglia",
    "Burnham-On-Sea, Taunton, South West",
    "Burnley, Blackburn, North West",
    "Burntisland, Kirkcaldy, Scotland",
    "Burntwood, Walsall, The Midlands",
    "Burry Port, Swansea, Wales",
    "Burton On Trent, Derby, The Midlands",
    "Bury St Edmunds, Ipswich, East Anglia",
    "Bury, Bolton, North West",
    "Bushey, Watford, London",
    "Bushmills, Belfast, Northern Ireland",
    "Buxton, Stockport, North West",
    "Cabinteely, Dublin South, Ireland",
    "Cabra, Dublin North, Ireland",
    "Caernarfon, Llandudno, Wales",
    "Caerphilly, Cardiff, Wales",
    "Caersws, Shrewsbury, Wales",
    "Cahir, Tipperary, Ireland",
    "Cairndow, Paisley, Scotland",
    "Caldicot, Newport, Wales",
    "Caledon, Belfast, Northern Ireland",
    "Callander, Falkirk, Scotland",
    "Callington, Plymouth, South West",
    "Calne, Swindon, South West",
    "Calstock, Plymouth, South West",
    "Camberley, Guildford, South East",
    "Camberwell, London SE, London",
    "Camborne, Truro, South West",
    "Cambridge, Cambridge, East Anglia",
    "Camden Town, London NW, London",
    "Camelford, Plymouth, South West",
    "Campbeltown, Paisley, Scotland",
    "Canning Town, London E, London",
    "Cannock, Walsall, The Midlands",
    "Cannon Street, London EC, London",
    "Canonbie, Dumfries, Scotland",
    "Canterbury, Canterbury, South East",
    "Canvey Island, Southend on Sea, East Anglia",
    "Capel St, Dublin City North, Ireland",
    "Cappagh, Dublin North, Ireland",
    "Cardiff, Cardiff, Wales",
    "Cardigan, Swansea, Wales",
    "Carlisle, Carlisle, North West",
    "Carlow, Carlow, Ireland",
    "Carluke, Motherwell, Scotland",
    "Carmarthen, Swansea, Wales",
    "Carnforth, Lancaster, North West",
    "Carnoustie, Dundee, Scotland",
    "Carrbridge, Perth, Scotland",
    "Carrick-on-Suir, Tipperary, Ireland",
    "Carrickfergus, Belfast, Northern Ireland",
    "Carrickmacross, Monaghan, Ireland",
    "Carrickmines, Dublin South, Ireland",
    "Carrigaline, Cork, Ireland",
    "Carshalton, Sutton, London",
    "Carterton, Oxford, South East",
    "Castle Cary, Bath, South West",
    "Castle Douglas, Dumfries, Scotland",
    "Castlebar, Mayo, Ireland",
    "Castlederg, Belfast, Northern Ireland",
    "Castleford, Wakefield, Yorkshire",
    "Castleknock, Dublin North, Ireland",
    "Castlewellan, Belfast, Northern Ireland",
    "Caterham, Croydon, London",
    "Catford, London SE, London",
    "Catterick Garrison, Darlington, North East",
    "Cavan, Cavan, Ireland",
    "Celbridge, Kildare, Ireland",
    "Cemaes Bay, Llandudno, Wales",
    "Central district, London SW, London",
    "Chalfont St Giles, Hemel Hempstead, South East",
    "Chapelizod, Dublin South, Ireland",
    "Chard, Taunton, South West",
    "Charing Cross, London WC, London",
    "Charlton, London SE, London",
    "Chatham, Rochester, South East",
    "Chathill, Newcastle upon Tyne, North East",
    "Chatteris, Peterborough, East Anglia",
    "Cheadle, Stockport, North West",
    "Cheddar, Bristol, South West",
    "Chelmsford, Chelmsford, East Anglia",
    "Chelsea, London SW, London",
    "Cheltenham, Gloucester, South West",
    "Chepstow, Newport, Wales",
    "Chertsey, Kingston upon Thames, London",
    "Chesham, Hemel Hempstead, South East",
    "Chessington, Kingston upon Thames, London",
    "Chester Le Street, Durham, North East",
    "Chester, Chester, North West",
    "Chesterfield, Sheffield, Yorkshire",
    "Chichester, Portsmouth, South East",
    "Chigwell, Ilford, London",
    "Chingford, London E, London",
    "Chinnor, Oxford, South East",
    "Chippenham, Swindon, South West",
    "Chipping Campden, Gloucester, South West",
    "Chipping Norton, Oxford, South East",
    "Chislehurst, Bromley, London",
    "Chiswick, London W, London",
    "Choppington, Newcastle upon Tyne, North East",
    "Chorley, Preston, North West",
    "Christchurch, Bournemouth, South East",
    "Chulmleigh, Exeter, South West",
    "Church Stretton, Shrewsbury, Wales",
    "Churchtown, Dublin South, Ireland",
    "Cinderford, Gloucester, South West",
    "Cirencester, Gloucester, South West",
    "Clackmannan, Falkirk, Scotland",
    "Clacton On Sea, Colchester, East Anglia",
    "Clane, Kildare, Ireland",
    "Clapham, London SW, London",
    "Clapton, London E, London",
    "Clarbeston Road, Swansea, Wales",
    "Cleator Moor, Carlisle, North West",
    "Cleator, Carlisle, North West",
    "Cleckheaton, Bradford, Yorkshire",
    "Cleethorpes, Doncaster, Yorkshire",
    "Clerkenwell, London EC, London",
    "Clevedon, Bristol, South West",
    "Clitheroe, Blackburn, North West",
    "Clogher, Belfast, Northern Ireland",
    "Clonakilty, Cork, Ireland",
    "Clondalkin, Dublin South, Ireland",
    "Clonee, Dublin North, Ireland",
    "Cloniffe, Dublin North, Ireland",
    "Clonmel, Tipperary, Ireland",
    "Clonshaugh, Dublin North, Ireland",
    "Clonsilla, Dublin North, Ireland",
    "Clonskeagh , Dublin South, Ireland",
    "Clontarf, Dublin North, Ireland",
    "Clydebank, Glasgow, Scotland",
    "Clynderwen, Swansea, Wales",
    "Coalville, Leicester, The Midlands",
    "Coatbridge, Motherwell, Scotland",
    "Cobh, Cork, Ireland",
    "Cobham, Kingston upon Thames, London",
    "Cockburnspath, Galashiels, Scotland",
    "Cockermouth, Carlisle, North West",
    "Colchester, Colchester, East Anglia",
    "Coldstream, Galashiels, Scotland",
    "Coleford, Gloucester, South West",
    "Coleraine, Belfast, Northern Ireland",
    "Colintraive, Paisley, Scotland",
    "College Green, Dublin City South, Ireland",
    "Colne, Blackburn, North West",
    "Colwyn Bay, Llandudno, Wales",
    "Colyton, Exeter, South West",
    "Congleton, Crewe, North West",
    "Coniston, Lancaster, North West",
    "Consett, Durham, North East",
    "Conwy, Llandudno, Wales",
    "Cookstown, Belfast, Northern Ireland",
    "Corbridge, Newcastle upon Tyne, North East",
    "Corby, Northampton, South East",
    "Corduff, Dublin North, Ireland",
    "Cork & Suburbs, Cork, Ireland",
    "Cornhill-On-Tweed, Galashiels, Scotland",
    "Corrour, Perth, Scotland",
    "Corsham, Swindon, South West",
    "Corwen, Llandudno, Wales",
    "Cottingham, Hull, Yorkshire",
    "Coulsdon, Croydon, London",
    "Covent Garden, London WC, London",
    "Coventry, Coventry, The Midlands",
    "Cowbridge, Cardiff, Wales",
    "Cowdenbeath, Kirkcaldy, Scotland",
    "Cowes, Portsmouth, South East",
    "Cradley Heath, Birmingham, The Midlands",
    "Craigavon, Belfast, Northern Ireland",
    "Cramlington, Newcastle upon Tyne, North East",
    "Cranbrook, Tonbridge, South East",
    "Cranleigh, Guildford, South East",
    "Craven Arms, Shrewsbury, Wales",
    "Crawley, Redhill, South East",
    "Crediton, Exeter, South West",
    "Cremore, Dublin North, Ireland",
    "Crewe, Crewe, North West",
    "Crewkerne, Taunton, South West",
    "Crianlarich, Falkirk, Scotland",
    "Criccieth, Llandudno, Wales",
    "Crickhowell, Newport, Wales",
    "Cricklewood, London NW, London",
    "Crieff, Perth, Scotland",
    "Cromarty, Inverness, Scotland",
    "Cromer, Norwich, East Anglia",
    "Crook, Darlington, North East",
    "Crowborough, Tonbridge, South East",
    "Crowthorne, Reading, South East",
    "Croydon, Croydon, London",
    "Crumlin, Belfast, Northern Ireland",
    "Crumlin, Dublin South, Ireland",
    "Crymych, Swansea, Wales",
    "Cullompton, Exeter, South West",
    "Cumnock, Kilmarnock, Scotland",
    "Cupar, Kirkcaldy, Scotland",
    "Currie, Edinburgh, Scotland",
    "Cwmbran, Newport, Wales",
    "Dagenham, Romford, London",
    "Dalbeattie, Dumfries, Scotland",
    "Dalkeith, Edinburgh, Scotland",
    "Dalmally, Paisley, Scotland",
    "Dalry, Kilmarnock, Scotland",
    "Dalton-In-Furness, Lancaster, North West",
    "Dalwhinnie, Perth, Scotland",
    "Darlington, Darlington, North East",
    "Darndale, Dublin North, Ireland",
    "Dartford, Dartford, South East",
    "Dartmouth, Torquay, South West",
    "Dartry, Dublin South, Ireland",
    "Darvel, Kilmarnock, Scotland",
    "Darwen, Blackburn, North West",
    "Daventry, Northampton, South East",
    "Dawlish, Exeter, South West",
    "Deal, Canterbury, South East",
    "Deeside, Chester, North West",
    "Delabole, Plymouth, South West",
    "Denbigh, Llandudno, Wales",
    "Denny, Falkirk, Scotland",
    "Deptford, London SE, London",
    "Derby, Derby, The Midlands",
    "Dereham, Norwich, East Anglia",
    "Devizes, Swindon, South West",
    "Dewsbury, Wakefield, Yorkshire",
    "Didcot, Oxford, South East",
    "Dinas Powys, Cardiff, Wales",
    "Dingwall, Inverness, Scotland",
    "Diss, Ipswich, East Anglia",
    "Dolgellau, Llandudno, Wales",
    "Dollar, Falkirk, Scotland",
    "Dollis Hill, London NW, London",
    "Dollymount, Dublin North, Ireland",
    "Dolphin's Barn, Dublin South, Ireland",
    "Dolwyddelan, Llandudno, Wales",
    "Donabate, Dublin, Ireland",
    "Donaghadee, Belfast, Northern Ireland",
    "Donaghmede, Dublin North, Ireland",
    "Doncaster, Doncaster, Yorkshire",
    "Donnybrook, Dublin South, Ireland",
    "Dorchester, Dorchester, South West",
    "Dorking, Redhill, South East",
    "Dornoch, Inverness, Scotland",
    "Dorset St, Dublin City North, Ireland",
    "Doune, Falkirk, Scotland",
    "Dover, Canterbury, South East",
    "Downham Market, Peterborough, East Anglia",
    "Downpatrick, Belfast, Northern Ireland",
    "Driffield, York, Yorkshire",
    "Drimnagh, Dublin South, Ireland",
    "Drogheda, Louth, Ireland",
    "Droitwich, Worcester, The Midlands",
    "Dromore, Belfast, Northern Ireland",
    "Dronfield, Sheffield, Yorkshire",
    "Drumcondra, Dublin North, Ireland",
    "Drury Lane, London WC, London",
    "Drybrook, Gloucester, South West",
    "Dubber, Dublin North, Ireland",
    "Dublin & Suburbs, Dublin, Ireland",
    "Dudley, Dudley, The Midlands",
    "Dukinfield, Stockport, North West",
    "Dulas, Llandudno, Wales",
    "Duleek, Meath, Ireland",
    "Dulverton, Taunton, South West",
    "Dulwich, London SE, London",
    "Dumbarton, Glasgow, Scotland",
    "Dumfries, Dumfries, Scotland",
    "Dun Laoghaire, Dublin South, Ireland",
    "Dunbar, Edinburgh, Scotland",
    "Dunbeath, Kirkwall, Scotland",
    "Dunblane, Falkirk, Scotland",
    "Dunboyne, Meath, Ireland",
    "Dundalk & Suburbs, Louth, Ireland",
    "Dundee, Dundee, Scotland",
    "Dundrum, Dublin South, Ireland",
    "Dunfermline, Kirkcaldy, Scotland",
    "Dungannon, Belfast, Northern Ireland",
    "Dungarvan, Waterford, Ireland",
    "Dunkeld, Perth, Scotland",
    "Dunmow, Chelmsford, East Anglia",
    "Dunoon, Paisley, Scotland",
    "Duns, Galashiels, Scotland",
    "Dunshaughlin, Meath, Ireland",
    "Dunstable, Luton, London",
    "Durham, Durham, North East",
    "Dursley, Gloucester, South West",
    "Dyffryn Ardudwy, Llandudno, Wales",
    "Dymock, Gloucester, South West",
    "Ealing, London W, London",
    "Earls Court, London SW, London",
    "Earlston, Galashiels, Scotland",
    "East Boldon, Newcastle upon Tyne, North East",
    "East Cowes, Portsmouth, South East",
    "East Dulwich, London SE, London",
    "East Finchley, London N, London",
    "East Grinstead, Redhill, South East",
    "East Ham, London E, London",
    "East Linton, Edinburgh, Scotland",
    "East Molesey, Kingston upon Thames, London",
    "East Wall, Dublin North, Ireland",
    "Eastbourne, Brighton, South East",
    "Eastleigh, Southampton, South East",
    "Ebbw Vale, Newport, Wales",
    "Edenbridge, Tonbridge, South East",
    "Edenderry, Offaly, Ireland",
    "Edgware, Harrow, London",
    "Edinburgh, Edinburgh, Scotland",
    "Egham, Twickenham, London",
    "Egremont, Carlisle, North West",
    "Ekm Mont, Dublin North, Ireland",
    "Elgin, Inverness, Scotland",
    "Elland, Halifax, Yorkshire",
    "Ellesmere Port, Chester, North West",
    "Ellesmere, Shrewsbury, Wales",
    "Ellon, Aberdeen, Scotland",
    "Eltham, London SE, London",
    "Ely, Cambridge, East Anglia",
    "Emsworth, Portsmouth, South East",
    "Enfield, Enfield, London",
    "Ennis, Clare, Ireland",
    "Enniscorthy, Wexford, Ireland",
    "Enniskillen, Belfast, Northern Ireland",
    "Epping, Chelmsford, East Anglia",
    "Epsom, Kingston upon Thames, London",
    "Erith, Dartford, South East",
    "Erskine, Paisley, Scotland",
    "Esher, Kingston upon Thames, London",
    "Etchingham, Tonbridge, South East",
    "Evesham, Worcester, The Midlands",
    "Exeter, Exeter, South West",
    "Exmouth, Exeter, South West",
    "Eye, Ipswich, East Anglia",
    "Eyemouth, Galashiels, Scotland",
    "Fairbourne, Llandudno, Wales",
    "Fairford, Gloucester, South West",
    "Fairview, Dublin North, Ireland",
    "Fakenham, Norwich, East Anglia",
    "Falkirk, Falkirk, Scotland",
    "Falmouth, Truro, South West",
    "Fareham, Portsmouth, South East",
    "Faringdon, Swindon, South West",
    "Farnborough, Guildford, South East",
    "Farnham, Guildford, South East",
    "Faversham, Rochester, South East",
    "Felixstowe, Ipswich, East Anglia",
    "Feltham, Twickenham, London",
    "Fenchurch Street, London EC, London",
    "Fermoy, Cork, Ireland",
    "Ferndale, Cardiff, Wales",
    "Ferndown, Bournemouth, South East",
    "Ferryhill, Darlington, North East",
    "Ferryside, Swansea, Wales",
    "Fetter Lane, London EC, London",
    "Filey, York, Yorkshire",
    "Finchley, London N, London",
    "Finglas, Dublin North, Ireland",
    "Finsbury Park, London N, London",
    "Finsbury, London EC, London",
    "Firhouse, Dublin South, Ireland",
    "Fishguard, Swansea, Wales",
    "Fitzwilliam Square, Dublin City South, Ireland",
    "Fivemiletown, Belfast, Northern Ireland",
    "Fleet Street, London EC, London",
    "Fleet, Guildford, South East",
    "Fleetwood, Blackpool, North West",
    "Flint, Chester, North West",
    "Fochabers, Inverness, Scotland",
    "Folkestone, Canterbury, South East",
    "Fordingbridge, Salisbury, South West",
    "Forest Gate, London E, London",
    "Forest Hill, London SE, London",
    "Forest Row, Redhill, South East",
    "Forfar, Dundee, Scotland",
    "Forres, Inverness, Scotland",
    "Forsinard, Kirkwall, Scotland",
    "Fort Augustus, Perth, Scotland",
    "Fort William, Perth, Scotland",
    "Fortrose, Inverness, Scotland",
    "Four Courts , Dublin North, Ireland",
    "Fowey, Plymouth, South West",
    "Foxrock, Dublin South, Ireland",
    "Fraserburgh, Aberdeen, Scotland",
    "Freshwater, Portsmouth, South East",
    "Frinton On Sea, Colchester, East Anglia",
    "Frizington, Carlisle, North West",
    "Frodsham, Warrington, North West",
    "Frome, Bath, South West",
    "Fulham, London SW, London",
    "Gaerwen, Llandudno, Wales",
    "Gainsborough, Doncaster, Yorkshire",
    "Gairloch, Inverness, Scotland",
    "Galashiels, Galashiels, Scotland",
    "Galston, Kilmarnock, Scotland",
    "Galway & Suburbs, Galway, Ireland",
    "Garndolbenmaen, Llandudno, Wales",
    "Garve, Inverness, Scotland",
    "Gateshead, Newcastle upon Tyne, North East",
    "Gatwick, Redhill, South East",
    "Gerrards Cross, Slough, London",
    "Gillingham, Rochester, South East",
    "Gillingham, Salisbury, South West",
    "Girvan, Kilmarnock, Scotland",
    "Glasgow, Glasgow, Scotland",
    "Glastonbury, Bath, South West",
    "Glenfinnan, Perth, Scotland",
    "Glenrothes, Kirkcaldy, Scotland",
    "Glogue, Swansea, Wales",
    "Glossop, Stockport, North West",
    "Gloucester, Gloucester, South West",
    "Goatstown, Dublin South, Ireland",
    "Godalming, Guildford, South East",
    "Godstone, Redhill, South East",
    "Golders Green, London NW, London",
    "Golspie, Kirkwall, Scotland",
    "Goodwick, Swansea, Wales",
    "Goole, Doncaster, Yorkshire",
    "Gordon, Galashiels, Scotland",
    "Gorebridge, Edinburgh, Scotland",
    "Gorey, Wexford, Ireland",
    "Gosport, Portsmouth, South East",
    "Gourock, Paisley, Scotland",
    "Grange-Over-Sands, Lancaster, North West",
    "Grangemouth, Falkirk, Scotland",
    "Grantham, Nottingham, The Midlands",
    "Grantown-On-Spey, Perth, Scotland",
    "Gravesend, Dartford, South East",
    "Gray's Inn, London WC, London",
    "Grays, Romford, London",
    "Great Missenden, Hemel Hempstead, South East",
    "Great Ormond Street Hospital, London WC, London",
    "Great Yarmouth, Norwich, East Anglia",
    "Greenford, Southall, London",
    "Greenhithe, Dartford, South East",
    "Greenock, Paisley, Scotland",
    "Greenwich, London SE, London",
    "Gretna, Dumfries, Scotland",
    "Greystones, Wicklow, Ireland",
    "Griffith Avenue, Dublin North, Ireland",
    "Grimsby, Doncaster, Yorkshire",
    "Guernsey, Guernsey, South East",
    "Guildford, Guildford, South East",
    "Guildhall, London EC, London",
    "Guisborough, Cleveland, North East",
    "Gullane, Edinburgh, Scotland",
    "Gunnislake, Plymouth, South West",
    "Hackney, London E, London",
    "Haddington, Edinburgh, Scotland",
    "Hailsham, Brighton, South East",
    "Halesowen, Birmingham, The Midlands",
    "Halesworth, Ipswich, East Anglia",
    "Halifax, Halifax, Yorkshire",
    "Halkirk, Kirkwall, Scotland",
    "Halstead, Colchester, East Anglia",
    "Haltwhistle, Newcastle upon Tyne, North East",
    "Hamilton, Motherwell, Scotland",
    "Hammersmith, London W, London",
    "Hampstead, London NW, London",
    "Hampton, Twickenham, London",
    "Hanwell, London W, London",
    "Harcourt Street, Dublin City South, Ireland",
    "Harlech, Llandudno, Wales",
    "Harleston, Ipswich, East Anglia",
    "Harlow, Chelmsford, East Anglia",
    "Harmonstown, Dublin North, Ireland",
    "Harold's Cross , Dublin South, Ireland",
    "Harpenden, St Albans, London",
    "Harrogate, Harrogate, Yorkshire",
    "Harrow, Harrow, London",
    "Hartfield, Tonbridge, South East",
    "Hartlepool, Cleveland, North East",
    "Harwich, Colchester, East Anglia",
    "Haslemere, Guildford, South East",
    "Hassocks, Brighton, South East",
    "Hastings, Tonbridge, South East",
    "Hatfield, St Albans, London",
    "Hatton Garden, London EC, London",
    "Havant, Portsmouth, South East",
    "Haverfordwest, Swansea, Wales",
    "Haverhill, Cambridge, East Anglia",
    "Hawes, Darlington, North East",
    "Hawick, Galashiels, Scotland",
    "Hayes, Southall, London",
    "Hayle, Truro, South West",
    "Hayling Island, Portsmouth, South East",
    "Haywards Heath, Redhill, South East",
    "Heanor, Derby, The Midlands",
    "Heathfield, Tonbridge, South East",
    "Hebburn, Newcastle upon Tyne, North East",
    "Hebden Bridge, Halifax, Yorkshire",
    "Heckmondwike, Wakefield, Yorkshire",
    "Helensburgh, Glasgow, Scotland",
    "Helmsdale, Kirkwall, Scotland",
    "Helston, Truro, South West",
    "Hemel Hempstead, Hemel Hempstead, South East",
    "Hendon, London NW, London",
    "Henfield, Brighton, South East",
    "Hengoed, Cardiff, Wales",
    "Henley In Arden, Birmingham, The Midlands",
    "Henley-On-Thames, Reading, South East",
    "Henlow, Stevenage, East Anglia",
    "Henry St, Dublin City North, Ireland",
    "Hereford, Hereford, The Midlands",
    "Heriot, Edinburgh, Scotland",
    "Herne Bay, Canterbury, South East",
    "Herne Hill, London SE, London",
    "Hertford, Stevenage, East Anglia",
    "Hessle, Hull, Yorkshire",
    "Hexham, Newcastle upon Tyne, North East",
    "Heywood, Oldham, North West",
    "High Holborn, London WC, London",
    "High Peak, Stockport, North West",
    "High Wycombe, Hemel Hempstead, South East",
    "Highbridge, Taunton, South West",
    "Highbury, London N, London",
    "Highgate, London N, London",
    "Hillsborough, Belfast, Northern Ireland",
    "Hinckley, Leicester, The Midlands",
    "Hindhead, Guildford, South East",
    "Hinton St George, Taunton, South West",
    "Hitchin, Stevenage, East Anglia",
    "Hockley, Southend on Sea, East Anglia",
    "Hoddesdon, Enfield, London",
    "Holborn & Strand, London WC, London",
    "Holloway, London N, London",
    "Holmfirth, Huddersfield, Yorkshire",
    "Holmrook, Carlisle, North West",
    "Holsworthy, Exeter, South West",
    "Holt, Norwich, East Anglia",
    "Holyhead, Llandudno, Wales",
    "Holywell, Chester, North West",
    "Holywood, Belfast, Northern Ireland",
    "Homerton, London E, London",
    "Honiton, Exeter, South West",
    "Hook, Reading, South East",
    "Hope Valley, Sheffield, Yorkshire",
    "Horley, Redhill, South East",
    "Horncastle, Lincoln, East Anglia",
    "Hornchurch, Romford, London",
    "Hornsea, Hull, Yorkshire",
    "Hornsey, London N, London",
    "Horsham, Redhill, South East",
    "Houghton Le Spring, Durham, North East",
    "Hounslow, Twickenham, London",
    "Hove, Brighton, South East",
    "Howth , Dublin North, Ireland",
    "Huddersfield, Huddersfield, Yorkshire",
    "Hull, Hull, Yorkshire",
    "Humbie, Edinburgh, Scotland",
    "Hungerford, Reading, South East",
    "Hunstanton, Peterborough, East Anglia",
    "Huntingdon, Peterborough, East Anglia",
    "Huntly, Aberdeen, Scotland",
    "Hyde, Stockport, North West",
    "Hythe, Canterbury, South East",
    "Ibstock, Leicester, The Midlands",
    "Ilford, Ilford, London",
    "Ilfracombe, Exeter, South West",
    "Ilkeston, Derby, The Midlands",
    "Ilkley, Leeds, Yorkshire",
    "Ilminster, Taunton, South West",
    "Immingham, Doncaster, Yorkshire",
    "Inchicore, Dublin South, Ireland",
    "Ingatestone, Chelmsford, East Anglia",
    "Innerleithen, Edinburgh, Scotland",
    "Insch, Aberdeen, Scotland",
    "Inveraray, Paisley, Scotland",
    "Invergarry, Perth, Scotland",
    "Invergordon, Inverness, Scotland",
    "Inverkeithing, Kirkcaldy, Scotland",
    "Inverness, Inverness, Scotland",
    "Inverurie, Aberdeen, Scotland",
    "Ipswich, Ipswich, East Anglia",
    "Irishtown, Dublin South, Ireland",
    "Irvine, Kilmarnock, Scotland",
    "Island Bridge, Dublin South, Ireland",
    "Isle Of Arran, Kilmarnock, Scotland",
    "Isle Of Barra, Outer Hebrides, Scotland",
    "Isle Of Benbecula, Outer Hebrides, Scotland",
    "Isle Of Bute, Paisley, Scotland",
    "Isle Of Canna, Perth, Scotland",
    "Isle Of Coll, Paisley, Scotland",
    "Isle Of Colonsay, Paisley, Scotland",
    "Isle Of Cumbrae, Kilmarnock, Scotland",
    "Isle Of Dogs, Ilford, London",
    "Isle Of Eigg, Perth, Scotland",
    "Isle Of Gigha, Paisley, Scotland",
    "Isle Of Harris, Outer Hebrides, Scotland",
    "Isle Of Iona, Paisley, Scotland",
    "Isle Of Islay, Paisley, Scotland",
    "Isle Of Jura, Paisley, Scotland",
    "Isle Of Lewis, Outer Hebrides, Scotland",
    "Isle of Man, Isle of Man, North West",
    "Isle Of Mull, Paisley, Scotland",
    "Isle Of North Uist, Outer Hebrides, Scotland",
    "Isle Of Rum, Perth, Scotland",
    "Isle Of Scalpay, Outer Hebrides, Scotland",
    "Isle Of Skye, Inverness, Scotland",
    "Isle Of South Uist, Outer Hebrides, Scotland",
    "Isle Of Tiree, Paisley, Scotland",
    "Isles Of Scilly, Truro, South West",
    "Isleworth, Twickenham, London",
    "Islington, London N, London",
    "Iver, Slough, London",
    "Ivybridge, Plymouth, South West",
    "Jamestown, Dublin North, Ireland",
    "Jarrow, Newcastle upon Tyne, North East",
    "Jedburgh, Galashiels, Scotland",
    "Jersey, Inverness, Scotland",
    "Jobstown, Dublin South, Ireland",
    "Johnstone, Paisley, Scotland",
    "Juniper Green, Edinburgh, Scotland",
    "Keighley, Bradford, Yorkshire",
    "Keith, Aberdeen, Scotland",
    "Kells, Meath, Ireland",
    "Kelso, Galashiels, Scotland",
    "Kelty, Kirkcaldy, Scotland",
    "Kendal, Lancaster, North West",
    "Kenilworth, Coventry, The Midlands",
    "Kenley, Croydon, London",
    "Kennington, London SE, London",
    "Kensington, London W, London",
    "Kentish Town, London NW, London",
    "Keston, Bromley, London",
    "Keswick, Carlisle, North West",
    "Kettering, Northampton, South East",
    "Kidderminster, Dudley, The Midlands",
    "Kidlington, Oxford, South East",
    "Kidwelly, Swansea, Wales",
    "Kilbirnie, Kilmarnock, Scotland",
    "Kilburn, London NW, London",
    "Kilcock, Kildare, Ireland",
    "Kilcoole, Wicklow, Ireland",
    "Kildare Street, Dublin City South, Ireland",
    "Kildare, Kildare, Ireland",
    "Kilgetty, Swansea, Wales",
    "Kilkenny, Kilkenny, Ireland",
    "Killarney, Kerry, Ireland",
    "Killin, Falkirk, Scotland",
    "Kilmacolm, Paisley, Scotland",
    "Kilmainham, Dublin South, Ireland",
    "Kilmarnock, Kilmarnock, Scotland",
    "Kilnamanagh, Dublin South, Ireland",
    "Kilshane, Dublin North, Ireland",
    "Kilternan, Dublin South, Ireland",
    "Kilwinning, Kilmarnock, Scotland",
    "Kinbrace, Kirkwall, Scotland",
    "King's Lynn, Peterborough, East Anglia",
    "Kings Cross, London WC, London",
    "Kings Langley, Watford, London",
    "Kingsbridge, Torquay, South West",
    "Kingston Upon Thames, Kingston upon Thames, London",
    "Kingswinford, Dudley, The Midlands",
    "Kington, Hereford, The Midlands",
    "Kingussie, Perth, Scotland",
    "Kinlochleven, Perth, Scotland",
    "Kinross, Kirkcaldy, Scotland",
    "Kinsale, Cork, Ireland",
    "Kinsealy-Drinan, Dublin, Ireland",
    "Kirkby Stephen, Carlisle, North West",
    "Kirkby-In-Furness, Lancaster, North West",
    "Kirkcaldy, Kirkcaldy, Scotland",
    "Kirkcudbright, Dumfries, Scotland",
    "Kirkliston, Edinburgh, Scotland",
    "Kirknewton, Edinburgh, Scotland",
    "Kirkwall, Kirkwall, Scotland",
    "Kirriemuir, Dundee, Scotland",
    "Knaresborough, Harrogate, Yorkshire",
    "Knebworth, Stevenage, East Anglia",
    "Knighton, Llandrindod Wells, Wales",
    "Knocklyon, Dublin South, Ireland",
    "Knottingley, Wakefield, Yorkshire",
    "Knutsford, Warrington, North West",
    "Kyle, Inverness, Scotland",
    "Lairg, Inverness, Scotland",
    "Lampeter, Swansea, Wales",
    "Lanark, Motherwell, Scotland",
    "Lancaster, Lancaster, North West",
    "Lancing, Brighton, South East",
    "Langholm, Dumfries, Scotland",
    "Langport, Taunton, South West",
    "Larbert, Falkirk, Scotland",
    "Largs, Kilmarnock, Scotland",
    "Larkhall, Motherwell, Scotland",
    "Larne, Belfast, Northern Ireland",
    "Lasswade, Edinburgh, Scotland",
    "Latheron, Kirkwall, Scotland",
    "Lauder, Galashiels, Scotland",
    "Launceston, Plymouth, South West",
    "Laurencekirk, Aberdeen, Scotland",
    "Laytown-Bettystown-Mornington, Meath, Ireland",
    "Leadenhall, London EC, London",
    "Leamington Spa, Coventry, The Midlands",
    "Leatherhead, Kingston upon Thames, London",
    "Lechlade, Gloucester, South West",
    "Ledbury, Hereford, The Midlands",
    "Lee, London SE, London",
    "Lee-On-The-Solent, Portsmouth, South East",
    "Leeds, Leeds, Yorkshire",
    "Leek, Stoke on Trent, The Midlands",
    "Leeson Street Upper and Lower , Dublin City South, Ireland",
    "Leicester Square, London WC, London",
    "Leicester, Leicester, The Midlands",
    "Leigh, Wigan, North West",
    "Leigh-On-Sea, Southend on Sea, East Anglia",
    "Leighton Buzzard, Luton, London",
    "Leiston, Ipswich, East Anglia",
    "Leixlip, Kildare, Ireland",
    "Leominster, Hereford, The Midlands",
    "Leopardstown , Dublin South, Ireland",
    "Letchworth Garden City, Stevenage, East Anglia",
    "Letterkenny, Donegal, Ireland",
    "Leven, Kirkcaldy, Scotland",
    "Lewes, Brighton, South East",
    "Lewisham, London SE, London",
    "Leyburn, Darlington, North East",
    "Leyland, Preston, North West",
    "Leyton, London E, London",
    "Leytonstone, London E, London",
    "Lichfield, Walsall, The Midlands",
    "Lifton, Plymouth, South West",
    "Lightwater, Guildford, South East",
    "Limavady, Belfast, Northern Ireland",
    "Limerick & Suburbs, Limerick, Ireland",
    "Lincoln's Inn Fields, London WC, London",
    "Lincoln, Lincoln, East Anglia",
    "Lingfield, Redhill, South East",
    "Linlithgow, Edinburgh, Scotland",
    "Liphook, Guildford, South East",
    "Lisburn, Belfast, Northern Ireland",
    "Liskeard, Plymouth, South West",
    "Liss, Guildford, South East",
    "Listowel, Kerry, Ireland",
    "Littleborough, Oldham, North West",
    "Littlehampton, Brighton, South East",
    "Liverpool, Liverpool, North West",
    "Liversedge, Wakefield, Yorkshire",
    "Livingston, Edinburgh, Scotland",
    "Llanarth, Swansea, Wales",
    "Llanbedr, Llandudno, Wales",
    "Llanbedrgoch, Llandudno, Wales",
    "Llanbrynmair, Shrewsbury, Wales",
    "Llandeilo, Swansea, Wales",
    "Llandinam, Shrewsbury, Wales",
    "Llandovery, Swansea, Wales",
    "Llandrindod Wells, Llandrindod Wells, Wales",
    "Llandudno Junction, Llandudno, Wales",
    "Llandudno, Llandudno, Wales",
    "Llandysul, Swansea, Wales",
    "Llanelli, Swansea, Wales",
    "Llanelwedd, Llandrindod Wells, Wales",
    "Llanerchymedd, Llandudno, Wales",
    "Llanfairfechan, Llandudno, Wales",
    "Llanfairpwllgwyngyll, Llandudno, Wales",
    "Llanfechain, Shrewsbury, Wales",
    "Llanfyllin, Shrewsbury, Wales",
    "Llanfyrnach, Swansea, Wales",
    "Llangadog, Swansea, Wales",
    "Llangammarch Wells, Llandrindod Wells, Wales",
    "Llangefni,Llangollen, Llandudno, Wales",
    "Llanidloes, Shrewsbury, Wales",
    "Llanon, Shrewsbury, Wales",
    "Llanrhystud, Shrewsbury, Wales",
    "Llanrwst, Llandudno, Wales",
    "Llansantffraid, Shrewsbury, Wales",
    "Llantwit Major, Cardiff, Wales",
    "Llanwrda, Swansea, Wales",
    "Llanwrtyd Wells, Llandrindod Wells, Wales",
    "Llanybydder, Swansea, Wales",
    "Llanymynech, Shrewsbury, Wales",
    "Llwyngwril, Llandudno, Wales",
    "Loanhead, Edinburgh, Scotland",
    "Lochailort, Perth, Scotland",
    "Lochearnhead, Falkirk, Scotland",
    "Lochgelly, Kirkcaldy, Scotland",
    "Lochgilphead, Paisley, Scotland",
    "Lochwinnoch, Paisley, Scotland",
    "Lockerbie, Dumfries, Scotland",
    "London, London W, London",
    "Londonderry, Belfast, Northern Ireland",
    "Longfield, Dartford, South East",
    "Longford, Longford, Ireland",
    "Longhope, Gloucester, South West",
    "Longniddry, Edinburgh, Scotland",
    "Looe, Plymouth, South West",
    "Lord Edward Street, Dublin City South, Ireland",
    "Lossiemouth, Inverness, Scotland",
    "Lostwithiel, Plymouth, South West",
    "Loughborough, Leicester, The Midlands",
    "Loughrea, Galway, Ireland",
    "Loughton, Ilford, London",
    "Louth, Lincoln, East Anglia",
    "Lower Edmonton, London N, London",
    "Lowestoft, Norwich, East Anglia",
    "Ludlow, Shrewsbury, Wales",
    "Lusk, Dublin, Ireland",
    "Luton, Luton, London",
    "Lutterworth, Leicester, The Midlands",
    "Lybster, Kirkwall, Scotland",
    "Lydbrook, Gloucester, South West",
    "Lydbury North, Shrewsbury, Wales",
    "Lydney, Gloucester, South West",
    "Lyme Regis, Dorchester, South West",
    "Lymington, Southampton, South East",
    "Lymm, Warrington, North West",
    "Lyndhurst, Southampton, South East",
    "Lynmouth, Exeter, South West",
    "Lynton, Exeter, South West",
    "Lytham St Annes, Blackpool, North West",
    "Mablethorpe, Lincoln, East Anglia",
    "Macclesfield, Stockport, North West",
    "Macduff, Aberdeen, Scotland",
    "Machynlleth, Shrewsbury, Wales",
    "Macroom, Cork, Ireland",
    "Maesteg, Cardiff, Wales",
    "Maghera, Belfast, Northern Ireland",
    "Magherafelt, Belfast, Northern Ireland",
    "Maida Vale, London W, London",
    "Maidenhead, Slough, London",
    "Maidstone, Rochester, South East",
    "Malahide, Dublin, Ireland",
    "Maldon, Chelmsford, East Anglia",
    "Mallaig, Perth, Scotland",
    "Mallow, Cork, Ireland",
    "Malmesbury, Swindon, South West",
    "Malpas, Shrewsbury, Wales",
    "Malton, York, Yorkshire",
    "Malvern, Worcester, The Midlands",
    "Manchester, Manchester, North West",
    "Manningtree, Colchester, East Anglia",
    "Manor Park, London E, London",
    "Mansfield, Nottingham, The Midlands",
    "Mansion House, London EC, London",
    "Marazion, Truro, South West",
    "March, Peterborough, East Anglia",
    "Margate, Canterbury, South East",
    "Marianglas, Llandudno, Wales",
    "Marino , Dublin North, Ireland",
    "Market Drayton, Telford, The Midlands",
    "Market Harborough, Leicester, The Midlands",
    "Market Rasen, Lincoln, East Anglia",
    "Market Weighton, York, Yorkshire",
    "Markfield, Leicester, The Midlands",
    "Marlboro St, Dublin City North, Ireland",
    "Marlborough, Swindon, South West",
    "Marlow, Slough, London",
    "Martock, Taunton, South West",
    "Maryport, Carlisle, North West",
    "Matlock, Derby, The Midlands",
    "Mauchline, Kilmarnock, Scotland",
    "Maybole, Kilmarnock, Scotland",
    "Mayfield, Tonbridge, South East",
    "Maynooth, Kildare, Ireland",
    "Meifod, Shrewsbury, Wales",
    "Melksham, Swindon, South West",
    "Melrose, Galashiels, Scotland",
    "Melton Constable, Norwich, East Anglia",
    "Melton Mowbray, Leicester, The Midlands",
    "Menai Bridge, Llandudno, Wales",
    "Menstrie, Falkirk, Scotland",
    "Merchants Quay, Dublin South, Ireland",
    "Merrion Square, Dublin City South, Ireland",
    "Merrion, Dublin South, Ireland",
    "Merriott, Taunton, South West",
    "Merthyr Tydfil, Cardiff, Wales",
    "Mexborough, Sheffield, Yorkshire",
    "Middlesbrough, Cleveland, North East",
    "Middlewich, Crewe, North West",
    "Midhurst, Guildford, South East",
    "Midleton, Cork, Ireland",
    "Milford Haven, Swansea, Wales",
    "Mill Hill, London NW, London",
    "Millom, Lancaster, North West",
    "Milltimber, Aberdeen, Scotland",
    "Milnthorpe, Lancaster, North West",
    "Milton Keynes, Milton Keynes, London",
    "Mindrum, Galashiels, Scotland",
    "Minehead, Taunton, South West",
    "Mirfield, Wakefield, Yorkshire",
    "Mitcham, Croydon, London",
    "Mitcheldean, Gloucester, South West",
    "Mitchelstown, Cork, Ireland",
    "Moelfre, Llandudno, Wales",
    "Moffat, Dumfries, Scotland",
    "Mold, Chester, North West",
    "Monaghan, Monaghan, Ireland",
    "Monmouth, Newport, Wales",
    "Montacute, Taunton, South West",
    "Montgomery, Shrewsbury, Wales",
    "Montrose, Dundee, Scotland",
    "Monument, London EC, London",
    "Moor Row, Carlisle, North West",
    "Morden, Sutton, London",
    "Morecambe, Lancaster, North West",
    "Moreton In Marsh, Gloucester, South West",
    "Morpeth, Newcastle upon Tyne, North East",
    "Mortlake, London SW, London",
    "Motherwell, Motherwell, Scotland",
    "Mount Street Upper, and Lower, Dublin City South, Ireland",
    "Mountain Ash, Cardiff, Wales",
    "Mountjoy Sq, Dublin City North, Ireland",
    "Mountmellick, Laois, Ireland",
    "Much Hadham, Stevenage, East Anglia",
    "Much Wenlock, Telford, The Midlands",
    "Muir Of Ord, Inverness, Scotland",
    "Mulhuddart , Dublin North, Ireland",
    "Mullingar, Westmeath, Ireland",
    "Munlochy, Inverness, Scotland",
    "Musselburgh, Edinburgh, Scotland",
    "Muswell Hill, London N, London",
    "Naas, Kildare, Ireland",
    "Nairn, Inverness, Scotland",
    "Nantwich, Crewe, North West",
    "Narberth, Swansea, Wales",
    "Nassau Street, Dublin City South, Ireland",
    "Navan, Meath, Ireland",
    "Neath, Swansea, Wales",
    "Neilstown , Dublin South, Ireland",
    "Nelson, Blackburn, North West",
    "Nenagh, Tipperary, Ireland",
    "Neston, Chester, North West",
    "Nethy Bridge, Perth, Scotland",
    "New Cross, London SE, London",
    "New Malden, Kingston upon Thames, London",
    "New Milton, Bournemouth, South East",
    "New Oxford Street, London WC, London",
    "New Quay, Swansea, Wales",
    "New Romney, Tonbridge, South East",
    "New Ross, Wexford, Ireland",
    "New Southgate, London N, London",
    "New Tredegar, Newport, Wales",
    "Newark, Nottingham, The Midlands",
    "Newbiggin-By-The-Sea, Newcastle upon Tyne, North East",
    "Newbridge, Edinburgh, Scotland",
    "Newbridge, Kildare, Ireland",
    "Newbury, Reading, South East",
    "Newcastle Emlyn, Swansea, Wales",
    "Newcastle Upon Tyne, Newcastle upon Tyne, North East",
    "Newcastle West, Limerick, Ireland",
    "Newcastle, Belfast, Northern Ireland",
    "Newcastle, Stoke on Trent, The Midlands",
    "Newcastleton, Galashiels, Scotland",
    "Newent, Gloucester, South West",
    "Newhaven, Brighton, South East",
    "Newmarket, Cambridge, East Anglia",
    "Newmilns, Kilmarnock, Scotland",
    "Newnham, Gloucester, South West",
    "Newport On Tay, Dundee, Scotland",
    "Newport Pagnell, Milton Keynes, London",
    "Newport, Newport, Wales",
    "Newport, Portsmouth, South East",
    "Newport, Swansea, Wales",
    "Newport, Telford, The Midlands",
    "Newquay, Truro, South West",
    "Newry, Belfast, Northern Ireland",
    "Newton Abbot, Torquay, South West",
    "Newton Aycliffe, Darlington, North East",
    "Newton Le Willows, Warrington, North West",
    "Newton Stewart, Dumfries, Scotland",
    "Newtonmore, Perth, Scotland",
    "Newtown, Shrewsbury, Wales",
    "Newtownabbey, Belfast, Northern Ireland",
    "Newtownards, Belfast, Northern Ireland",
    "Normanton, Wakefield, Yorkshire",
    "North Berwick, Edinburgh, Scotland",
    "North Ferriby, Hull, Yorkshire",
    "North Finchley, London N, London",
    "North Kensington, London W, London",
    "North Shields, Newcastle upon Tyne, North East",
    "North Tawton, Exeter, South West",
    "North Wall, Dublin City North, Ireland",
    "North Walsham, Norwich, East Anglia",
    "Northallerton, Darlington, North East",
    "Northampton, Northampton, South East",
    "Northolt, Southall, London",
    "Northwich, Crewe, North West",
    "Northwood, Harrow, London",
    "Norwich, Norwich, East Anglia",
    "Norwood, London SE, London",
    "Notting Hill, London W, London",
    "Nottingham, Nottingham, The Midlands",
    "Nuneaton, Coventry, The Midlands",
    "O'Connell St, Dublin City North, Ireland",
    "Oakham, Leicester, The Midlands",
    "Oban, Paisley, Scotland",
    "Okehampton, Exeter, South West",
    "Old Broad Street, London EC, London",
    "Oldbawn, Dublin South, Ireland",
    "Oldbury, Birmingham, The Midlands",
    "Oldham, Oldham, North West",
    "Olney, Milton Keynes, London",
    "Omagh, Belfast, Northern Ireland",
    "Ongar, Chelmsford, East Anglia",
    "Oranmore, Galway, Ireland",
    "Orkney, Kirkwall, Scotland",
    "Ormskirk, Liverpool, North West",
    "Orpington, Bromley, London",
    "Ossett, Wakefield, Yorkshire",
    "Oswestry, Shrewsbury, Wales",
    "Otley, Leeds, Yorkshire",
    "Ottery St Mary, Exeter, South West",
    "Oxford, Oxford, South East",
    "Oxted, Redhill, South East",
    "Paddington, London W, London",
    "Padstow, Plymouth, South West",
    "Paignton, Torquay, South West",
    "Paisley, Paisley, Scotland",
    "Palmers Green, London N, London",
    "Palmerstown , Dublin South, Ireland",
    "Par, Plymouth, South West",
    "Parnell Sq, Dublin City North, Ireland",
    "Passage West, Cork, Ireland",
    "Pathhead, Edinburgh, Scotland",
    "Peacehaven, Brighton, South East",
    "Pearse Street, Dublin City South, Ireland",
    "Peckham, London SE, London",
    "Peebles, Edinburgh, Scotland",
    "Pembroke Dock, Swansea, Wales",
    "Pembroke, Dublin South, Ireland",
    "Pembroke, Swansea, Wales",
    "Penarth, Cardiff, Wales",
    "Pencader, Swansea, Wales",
    "Penge, London SE, London",
    "Penicuik, Edinburgh, Scotland",
    "Penmaenmawr, Llandudno, Wales",
    "Penrhyndeudraeth, Llandudno, Wales",
    "Penrith, Carlisle, North West",
    "Penryn, Truro, South West",
    "Pentraeth, Llandudno, Wales",
    "Pentre, Cardiff, Wales",
    "Penysarn, Llandudno, Wales",
    "Penzance, Truro, South West",
    "Perranporth, Truro, South West",
    "Pershore, Worcester, The Midlands",
    "Perth, Perth, Scotland",
    "Peterborough, Peterborough, East Anglia",
    "Peterculter, Aberdeen, Scotland",
    "Peterhead, Aberdeen, Scotland",
    "Peterlee, Sunderland, North East",
    "Petersfield, Guildford, South East",
    "Petworth, Guildford, South East",
    "Pevensey, Brighton, South East",
    "Pewsey, Swindon, South West",
    "Phibsboro, Dublin North, Ireland",
    "Pickering, York, Yorkshire",
    "Pinner, Harrow, London",
    "Pitlochry, Perth, Scotland",
    "Plaistow, London E, London",
    "Plockton, Inverness, Scotland",
    "Plymouth, Plymouth, South West",
    "Polegate, Brighton, South East",
    "Pontefract, Wakefield, Yorkshire",
    "Pontyclun, Cardiff, Wales",
    "Pontypool, Newport, Wales",
    "Pontypridd, Cardiff, Wales",
    "Poole, Bournemouth, South East",
    "Poplar, London E, London",
    "Port Glasgow, Paisley, Scotland",
    "Port Isaac, Plymouth, South West",
    "Port Talbot, Swansea, Wales",
    "Portarlington, Laois, Ireland",
    "Porth, Cardiff, Wales",
    "Porthcawl, Cardiff, Wales",
    "Porthmadog, Llandudno, Wales",
    "Portland, Dorchester, South West",
    "Portlaoise, Laois, Ireland",
    "Portmarnock, Dublin, Ireland",
    "Portobello, Dublin South, Ireland",
    "Portree, Inverness, Scotland",
    "Portrush, Belfast, Northern Ireland",
    "Portsmouth, Portsmouth, South East",
    "Portstewart, Belfast, Northern Ireland",
    "Potters Bar, Enfield, London",
    "Poulton Le Fylde, Blackpool, North West",
    "Prenton, Chester, North West",
    "Prescot, Liverpool, North West",
    "Prestatyn, Llandudno, Wales",
    "Presteigne, Llandrindod Wells, Wales",
    "Preston, Preston, North West",
    "Prestonpans, Edinburgh, Scotland",
    "Prestwick, Kilmarnock, Scotland",
    "Princes Risborough, Hemel Hempstead, South East",
    "Priorswood, Dublin North, Ireland",
    "Prudhoe, Newcastle upon Tyne, North East",
    "Pudsey, Leeds, Yorkshire",
    "Pulborough, Redhill, South East",
    "Purfleet, Romford, London",
    "Purley, Croydon, London",
    "Putney , London SW, London",
    "Pwllheli, Llandudno, Wales",
    "Queenborough, Rochester, South East",
    "Radlett, Watford, London",
    "Radstock, Bath, South West",
    "Raheny , Dublin North, Ireland",
    "Rainham, Romford, London",
    "Ramsgate, Canterbury, South East",
    "Ranelagh, Dublin South, Ireland",
    "Rathgar, Dublin South, Ireland",
    "Rathmines, Dublin South, Ireland",
    "Ratoath, Meath, Ireland",
    "Ravenglass, Carlisle, North West",
    "Rayleigh, Southend on Sea, East Anglia",
    "Reading, Reading, South East",
    "Redcar, Cleveland, North East",
    "Redditch, Birmingham, The Midlands",
    "Redhill, Redhill, South East",
    "Redruth, Truro, South West",
    "Reigate, Redhill, South East",
    "Renfrew, Paisley, Scotland",
    "Retford, Doncaster, Yorkshire",
    "Rhayader, Llandrindod Wells, Wales",
    "Rhosgoch, Llandudno, Wales",
    "Rhosneigr, Llandudno, Wales",
    "Rhyl, Llandudno, Wales",
    "Richmond, Darlington, North East",
    "Richmond, Twickenham, London",
    "Rickmansworth, Watford, London",
    "Riding Mill, Newcastle upon Tyne, North East",
    "Ringsend, Dublin South, Ireland",
    "Ringwood, Bournemouth, South East",
    "Ripley, Derby, The Midlands",
    "Ripon, Harrogate, Yorkshire",
    "Riverside , Dublin North, Ireland",
    "Robertsbridge, Tonbridge, South East",
    "Rochdale, Oldham, North West",
    "Rochester, Rochester, South East",
    "Rochford, Southend on Sea, East Anglia",
    "Roebuck, Dublin South, Ireland",
    "Rogart, Inverness, Scotland",
    "Romford, Romford, London",
    "Romney Marsh, Tonbridge, South East",
    "Romsey, Southampton, South East",
    "Roscommon, Roscommon, Ireland",
    "Roscrea, Tipperary, Ireland",
    "Rosewell, Edinburgh, Scotland",
    "Roslin, Edinburgh, Scotland",
    "Ross-On-Wye, Hereford, The Midlands",
    "Rossendale, Blackburn, North West",
    "Rotherham, Sheffield, Yorkshire",
    "Rotherhithe, London SE, London",
    "Rowland's Castle, Portsmouth, South East",
    "Rowlands Gill, Newcastle upon Tyne, North East",
    "Rowley Regis, Birmingham, The Midlands",
    "Roy Bridge, Perth, Scotland",
    "Royal Exchange, London EC, London",
    "Royston, Stevenage, East Anglia",
    "Ruardean, Gloucester, South West",
    "Rugby, Coventry, The Midlands",
    "Rugeley, Walsall, The Midlands",
    "Ruislip, Harrow, London",
    "Runcorn, Warrington, North West",
    "Rush, Dublin, Ireland",
    "Rushden, Northampton, South East",
    "Ruthin, Llandudno, Wales",
    "Ryde, Portsmouth, South East",
    "Rye, Tonbridge, South East",
    "Ryton, Newcastle upon Tyne, North East",
    "Saffron Walden, Cambridge, East Anglia",
    "Salcombe, Torquay, South West",
    "Sale, Manchester, North West",
    "Salford, Manchester, North West",
    "Salisbury, Salisbury, South West",
    "Sallins, Kildare, Ireland",
    "Saltash, Plymouth, South West",
    "Saltburn-By-The-Sea, Cleveland, North East",
    "Saltcoats, Kilmarnock, Scotland",
    "Sandbach, Crewe, North West",
    "Sandhurst, Guildford, South East",
    "Sandown, Portsmouth, South East",
    "Sandringham, Peterborough, East Anglia",
    "Sandwich, Canterbury, South East",
    "Sandy, Stevenage, East Anglia",
    "Sandyford , Dublin South, Ireland",
    "Sandyford , Dublin South, Ireland",
    "Sandyford, Dublin South, Ireland",
    "Sandymount , Dublin South, Ireland",
    "Sanquhar, Dumfries, Scotland",
    "Santry, Dublin North, Ireland",
    "Saundersfoot, Swansea, Wales",
    "Sawbridgeworth, Chelmsford, East Anglia",
    "Saxmundham, Ipswich, East Anglia",
    "Scarborough, York, Yorkshire",
    "Scunthorpe, Doncaster, Yorkshire",
    "Seaford, Brighton, South East",
    "Seaham, Sunderland, North East",
    "Seahouses, Newcastle upon Tyne, North East",
    "Seascale, Carlisle, North West",
    "Seaton, Exeter, South West",
    "Seaview, Portsmouth, South East",
    "Sedbergh, Lancaster, North West",
    "Selby, York, Yorkshire",
    "Selkirk, Galashiels, Scotland",
    "Settle, Bradford, Yorkshire",
    "Sevenoaks, Tonbridge, South East",
    "Shaftesbury, Salisbury, South West",
    "Shanklin, Portsmouth, South East",
    "Shannon, Clare, Ireland",
    "Sheerness, Rochester, South East",
    "Sheffield, Sheffield, Yorkshire",
    "Shefford, Stevenage, East Anglia",
    "Shepherds Bush, London W, London",
    "Shepperton, Twickenham, London",
    "Shepton Mallet, Bath, South West",
    "Sherborne, Dorchester, South West",
    "Sheringham, Norwich, East Anglia",
    "Shetland, Lerwick, Scotland",
    "Shifnal, Telford, The Midlands",
    "Shildon, Darlington, North East",
    "Shipley, Bradford, Yorkshire",
    "Shipston On Stour, Coventry, The Midlands",
    "Shoreditch, London EC, London",
    "Shoreham By Sea, Brighton, South East",
    "Shotts, Motherwell, Scotland",
    "Shrewsbury, Shrewsbury, Wales",
    "Sidcup, Dartford, South East",
    "Sidmouth, Exeter, South West",
    "Sittingbourne, Rochester, South East",
    "Skegness, Peterborough, East Anglia",
    "Skelmersdale, Wigan, North West",
    "Skelmorlie, Paisley, Scotland",
    "Skerries, Dublin, Ireland",
    "Skipton, Bradford, Yorkshire",
    "Sleaford, Nottingham, The Midlands",
    "Sligo, Sligo, Ireland",
    "Slough, Slough, London",
    "Smethwick, Birmingham, The Midlands",
    "Snodland, Rochester, South East",
    "Solihull, Birmingham, The Midlands",
    "Somerset House, London WC, London",
    "Somerton, Taunton, South West",
    "South Brent, Torquay, South West",
    "South Circular Road, Dublin South, Ireland",
    "South Croydon, Croydon, London",
    "South Great Georges Street, Dublin City South, Ireland",
    "South Kensington, London SW, London",
    "South Lambeth, London SW, London",
    "South Molton, Exeter, South West",
    "South Norwood, London SE, London",
    "South Ockendon, Romford, London",
    "South Petherton, Taunton, South West",
    "South Queensferry, Edinburgh, Scotland",
    "South Shields, Newcastle upon Tyne, North East",
    "South Tottenham, London N, London",
    "Southall, Southall, London",
    "Southam, Coventry, The Midlands",
    "Southampton, Southampton, South East",
    "Southend-On-Sea, Southend on Sea, East Anglia",
    "Southgate, London N, London",
    "Southminster, Chelmsford, East Anglia",
    "Southport, Preston, North West",
    "Southsea, Portsmouth, South East",
    "Southwell, Nottingham, The Midlands",
    "Southwold, Ipswich, East Anglia",
    "Sowerby Bridge, Halifax, Yorkshire",
    "Spalding, Peterborough, East Anglia",
    "Spean Bridge, Perth, Scotland",
    "Spennymoor, Darlington, North East",
    "Spilsby, Peterborough, East Anglia",
    "St Agnes, Truro, South West",
    "St Albans, St Albans, London",
    "St Andrews, Kirkcaldy, Scotland",
    "St Asaph, Llandudno, Wales",
    "St Austell, Plymouth, South West",
    "St Bartholomew's Hospital, London EC, London",
    "St Bees, Carlisle, North West",
    "St Columb, Truro, South West",
    "St Helens, Warrington, North West",
    "St Ives, Peterborough, East Anglia",
    "St Ives, Truro, South West",
    "St John's Wood, London NW, London",
    "St Leonards-On-Sea, Tonbridge, South East",
    "St Luke's, London EC, London",
    "St Mary Axe, London EC, London",
    "St Neots, Peterborough, East Anglia",
    "St Pancras, London WC, London",
    "St Paul's, London EC, London",
    "St. Stephen's Green, Dublin City South, Ireland",
    "Stafford, Stoke on Trent, The Midlands",
    "Staines, Twickenham, London",
    "Stalybridge, Stockport, North West",
    "Stamford, Peterborough, East Anglia",
    "Stanford-Le-Hope, Southend on Sea, East Anglia",
    "Stanley, Durham, North East",
    "Stanmore, Harrow, London",
    "Stansted, Chelmsford, East Anglia",
    "Stepaside, Dublin South, Ireland",
    "Stevenage, Stevenage, East Anglia",
    "Stevenston, Kilmarnock, Scotland",
    "Steyning, Brighton, South East",
    "Stirling, Falkirk, Scotland",
    "Stockbridge, Southampton, South East",
    "Stockport, Stockport, North West",
    "Stocksfield, Newcastle upon Tyne, North East",
    "Stockton-On-Tees, Cleveland, North East",
    "Stockwell, London SW, London",
    "Stoke Newington, London N, London",
    "Stoke On Trent, Stoke on Trent, The Midlands",
    "Stoke-Sub-Hamdon, Taunton, South West",
    "Stone, Stoke on Trent, The Midlands",
    "Stonehaven, Aberdeen, Scotland",
    "Stonehouse, Gloucester, South West",
    "Stornoway, Outer Hebrides, Scotland",
    "Stourbridge, Dudley, The Midlands",
    "Stourport On Severn, Dudley, The Midlands",
    "Stowmarket, Ipswich, East Anglia",
    "Strabane, Belfast, Northern Ireland",
    "Stranraer, Dumfries, Scotland",
    "Stratford Upon Avon, Coventry, The Midlands",
    "Stratford, London E, London",
    "Strathaven, Motherwell, Scotland",
    "Strathcarron, Inverness, Scotland",
    "Strathdon, Aberdeen, Scotland",
    "Strathpeffer, Inverness, Scotland",
    "Streatham, London SW, London",
    "Street, Bath, South West",
    "Strome Ferry, Inverness, Scotland",
    "Stromness, Kirkwall, Scotland",
    "Stroud, Gloucester, South West",
    "Studley, Birmingham, The Midlands",
    "Sturminster Newton, Dorchester, South West",
    "Sudbury, Colchester, East Anglia",
    "Sunbury On Thames, Twickenham, London",
    "Sunderland, Sunderland, North East",
    "Surbiton, Kingston upon Thames, London",
    "Sutton Coldfield, Birmingham, The Midlands",
    "Sutton, Dublin North, Ireland",
    "Sutton, Sutton, London",
    "Sutton-In-Ashfield, Nottingham, The Midlands",
    "Swadlincote, Derby, The Midlands",
    "Swaffham, Peterborough, East Anglia",
    "Swanage, Bournemouth, South East",
    "Swanley, Bromley, London",
    "Swanscombe, Dartford, South East",
    "Swansea, Swansea, Wales",
    "Swindon, Swindon, South West",
    "Swords, Dublin, Ireland",
    "Sydenham, London SE, London",
    "Tadcaster, Leeds, Yorkshire",
    "Tadley, Reading, South East",
    "Tadworth, Kingston upon Thames, London",
    "Tain, Inverness, Scotland",
    "Talbot St , Dublin City North, Ireland",
    "Tallaght , Dublin South, Ireland",
    "Talsarnau, Llandudno, Wales",
    "Talybont, Llandudno, Wales",
    "Talybont, Shrewsbury, Wales",
    "Tamworth, Birmingham, The Midlands",
    "Tarbert, Paisley, Scotland",
    "Tarporley, Crewe, North West",
    "Taunton, Taunton, South West",
    "Tavistock, Plymouth, South West",
    "Taynuilt, Paisley, Scotland",
    "Tayport, Dundee, Scotland",
    "Teddington, Twickenham, London",
    "Teignmouth, Torquay, South West",
    "Telford, Telford, The Midlands",
    "Temple, London EC, London",
    "Templecombe, Bath, South West",
    "Templeogue , Dublin South, Ireland",
    "Tenbury Wells, Worcester, The Midlands",
    "Tenby, Swansea, Wales",
    "Tenterden, Tonbridge, South East",
    "Terenure , Dublin South, Ireland",
    "Tetbury, Gloucester, South West",
    "Tewkesbury, Gloucester, South West",
    "Thame, Oxford, South East",
    "Thames Ditton, Kingston upon Thames, London",
    "Thamesmead, London SE, London",
    "Thatcham, Reading, South East",
    "The Coombe , Dublin South, Ireland",
    "The Hyde, London NW, London",
    "Thetford, Ipswich, East Anglia",
    "Thirsk, York, Yorkshire",
    "Thornhill, Dumfries, Scotland",
    "Thornton Heath, Croydon, London",
    "Thornton-Cleveleys, Blackpool, North West",
    "Thurles, Tipperary, Ireland",
    "Thurso, Kirkwall, Scotland",
    "Ticknock, Dublin South, Ireland",
    "Tidworth, Salisbury, South West",
    "Tighnabruaich, Paisley, Scotland",
    "Tilbury, Romford, London",
    "Tillicoultry, Falkirk, Scotland",
    "Tintagel, Plymouth, South West",
    "Tipperary, Tipperary, Ireland",
    "Tipton, Dudley, The Midlands",
    "Tiverton, Exeter, South West",
    "Todmorden, Oldham, North West",
    "Tonbridge, Tonbridge, South East",
    "Tonypandy, Cardiff, Wales",
    "Tooting, London SW, London",
    "Torpoint, Plymouth, South West",
    "Torquay, Torquay, South West",
    "Torrington, Exeter, South West",
    "Totland Bay, Portsmouth, South East",
    "Totnes, Torquay, South West",
    "Tottenham, London N, London",
    "Towcester, Northampton, South East",
    "Tower Hill, London EC, London",
    "Tralee, Kerry, Ireland",
    "Tramore, Waterford, Ireland",
    "Tranent, Edinburgh, Scotland",
    "Tredegar, Newport, Wales",
    "Trefriw, Llandudno, Wales",
    "Tregaron, Shrewsbury, Wales",
    "Treharris, Cardiff, Wales",
    "Treorchy, Cardiff, Wales",
    "Trim, Meath, Ireland",
    "Trimdon Station, Cleveland, North East",
    "Tring, Hemel Hempstead, South East",
    "Troon, Kilmarnock, Scotland",
    "Trowbridge, Bath, South West",
    "Truro, Truro, South West",
    "Tuam, Galway, Ireland",
    "Tullamore, Offaly, Ireland",
    "Tunbridge Wells, Tonbridge, South East",
    "Turriff, Aberdeen, Scotland",
    "Twickenham, Twickenham, London",
    "Ty Croes, Llandudno, Wales",
    "Tyn-Y-Gongl, Llandudno, Wales",
    "Tywyn, Llandudno, Wales",
    "Uckfield, Tonbridge, South East",
    "Ulceby, Doncaster, Yorkshire",
    "Ullapool, Inverness, Scotland",
    "Ulverston, Lancaster, North West",
    "Umberleigh, Exeter, South West",
    "University College London, London WC, London",
    "Upminster, Romford, London",
    "Upper Edmonton, London N, London",
    "Upper Holloway, London N, London",
    "Usk, Newport, Wales",
    "Uttoxeter, Stoke on Trent, The Midlands",
    "Uxbridge, Southall, London",
    "Ventnor, Portsmouth, South East",
    "Verwood, Bournemouth, South East",
    "Victoria, London SW, London",
    "Virginia Water, Guildford, South East",
    "Wadebridge, Plymouth, South West",
    "Wadelai , Dublin North, Ireland",
    "Wadhurst, Tonbridge, South East",
    "Wakefield, Wakefield, Yorkshire",
    "Walkerburn, Edinburgh, Scotland",
    "Walkinstown , Dublin South, Ireland",
    "Wallasey, Chester, North West",
    "Wallingford, Oxford, South East",
    "Wallington, Sutton, London",
    "Wallsend, Newcastle upon Tyne, North East",
    "Walsall, Walsall, The Midlands",
    "Walsingham, Norwich, East Anglia",
    "Waltham Abbey, Enfield, London",
    "Waltham Cross, Enfield, London",
    "Walthamstow, London E, London",
    "Walton On The Naze, Colchester, East Anglia",
    "Walton-On-Thames, Kingston upon Thames, London",
    "Walworth, London SE, London",
    "Wandsworth, London SW, London",
    "Wantage, Oxford, South East",
    "Ware, Stevenage, East Anglia",
    "Wareham, Bournemouth, South East",
    "Warlingham, Croydon, London",
    "Warminster, Bath, South West",
    "Warrington, Warrington, North West",
    "Warwick, Coventry, The Midlands",
    "Washington, Newcastle upon Tyne, North East",
    "Watchet, Taunton, South West",
    "Waterford & Suburbs, Waterford, Ireland",
    "Waterlooville, Portsmouth, South East",
    "Watford, Watford, London",
    "Watlington, Oxford, South East",
    "Wedmore, Bristol, South West",
    "Wednesbury, Walsall, The Midlands",
    "Welling, Dartford, South East",
    "Wellingborough, Northampton, South East",
    "Wellington, Taunton, South West",
    "Wells, Bath, South West",
    "Wells-Next-The-Sea, Norwich, East Anglia",
    "Welshpool, Shrewsbury, Wales",
    "Welwyn Garden City, St Albans, London",
    "Welwyn, St Albans, London",
    "Wembley, Harrow, London",
    "Wemyss Bay, Paisley, Scotland",
    "West Brompton, London SW, London",
    "West Bromwich, Birmingham, The Midlands",
    "West Byfleet, Kingston upon Thames, London",
    "West Calder, Edinburgh, Scotland",
    "West Drayton, Southall, London",
    "West Dulwich, London SE, London",
    "West Ealing, London W, London",
    "West End, London W, London",
    "West Kensington, London W, London",
    "West Kilbride, Kilmarnock, Scotland",
    "West Linton, Edinburgh, Scotland",
    "West Malling, Rochester, South East",
    "West Molesey, Kingston upon Thames, London",
    "West Norwood, London SE, London",
    "West Wickham, Bromley, London",
    "West Wimbledon, London SW, London",
    "Westbury On Severn, Gloucester, South West",
    "Westbury, Bath, South West",
    "Westcliff-On-Sea, Southend on Sea, East Anglia",
    "Westerham, Tonbridge, South East",
    "Westgate On Sea, Canterbury, South East",
    "Westhill, Aberdeen, Scotland",
    "Weston Super Mare, Bristol, South West",
    "Westport, Mayo, Ireland",
    "Wetherby, Leeds, Yorkshire",
    "Wexford, Wexford, Ireland",
    "Weybridge, Kingston upon Thames, London",
    "Weymouth, Dorchester, South West",
    "Whetstone, London N, London",
    "Whitby, York, Yorkshire",
    "Whitchurch, Reading, South East",
    "Whitchurch, Shrewsbury, Wales",
    "Whitechapel, London E, London",
    "Whitehall , Dublin North, Ireland",
    "Whitehaven, Carlisle, North West",
    "Whitland, Swansea, Wales",
    "Whitley Bay, Newcastle upon Tyne, North East",
    "Whitstable, Canterbury, South East",
    "Whyteleafe, Croydon, London",
    "Wick, Kirkwall, Scotland",
    "Wickford, Southend on Sea, East Anglia",
    "Wicklow, Wicklow, Ireland",
    "Widnes, Warrington, North West",
    "Wigan, Wigan, North West",
    "Wigston, Leicester, The Midlands",
    "Wigton, Carlisle, North West",
    "Willenhall, Wolverhampton, The Midlands",
    "Willesden, London NW, London",
    "Wilmslow, Stockport, North West",
    "Wimbledon, London SW, London",
    "Wimborne, Bournemouth, South East",
    "Wincanton, Bath, South West",
    "Winchelsea, Tonbridge, South East",
    "Winchester, Southampton, South East",
    "Winchmore Hill, London N, London",
    "Windermere, Lancaster, North West",
    "Windlesham, Guildford, South East",
    "Windsor, Slough, London",
    "Windy Arbour, Dublin South, Ireland",
    "Wingate, Cleveland, North East",
    "Winkleigh, Exeter, South West",
    "Winscombe, Bristol, South West",
    "Winsford, Crewe, North West",
    "Wirral, Chester, North West",
    "Wisbech, Peterborough, East Anglia",
    "Wishaw, Motherwell, Scotland",
    "Witham, Chelmsford, East Anglia",
    "Withernsea, Hull, Yorkshire",
    "Witney, Oxford, South East",
    "Woking, Guildford, South East",
    "Wokingham, Reading, South East",
    "Wolverhampton, Wolverhampton, The Midlands",
    "Wood Green, London N, London",
    "Woodbridge, Ipswich, East Anglia",
    "Woodford Green, Ilford, London",
    "Woodford, London E, London",
    "Woodhall Spa, Lincoln, East Anglia",
    "Woodstock, Oxford, South East",
    "Woolacombe, Exeter, South West",
    "Wooler, Newcastle upon Tyne, North East",
    "Woolwich, London SE, London",
    "Worcester Park, Kingston upon Thames, London",
    "Worcester, Worcester, The Midlands",
    "Workington, Carlisle, North West",
    "Worksop, Sheffield, Yorkshire",
    "Worthing, Brighton, South East",
    "Wotton-Under-Edge, Gloucester, South West",
    "Wrexham, Llandudno, Wales",
    "Wylam, Newcastle upon Tyne, North East",
    "Wymondham, Norwich, East Anglia",
    "Y Felinheli, Llandudno, Wales",
    "Yarm, Cleveland, North East",
    "Yarmouth, Portsmouth, South East",
    "Yateley, Guildford, South East",
    "Yelverton, Plymouth, South West",
    "Yeovil, Bath, South West",
    "York, York, Yorkshire",
    "Youghal, Cork, Ireland",
    "Ystrad Meurig, Shrewsbury, Wales",
  ]


  def default_value_name(kase)
    return "#{kase.authorised_user.name} c/o #{current_user.company.name}" rescue nil
  end

  def default_value_address(kase)
    return kase.authorised_user.address  rescue nil
  end

  def product_bundle_list(product)
    bundle_list = []
    Bundles.instances.each do |bundle|
        bundle.products.each do |p|  
            puts p.to_s.camelize
            product_name = p.to_s.camelize
            bundle_list.push(bundle.class.name.demodulize) if product_name == product
        end  
    end
    return bundle_list.join(",")
  end
end
